// sanity/mockData.ts
import { Product, Category, Brand, StoreSettings } from '@/utils/types';

export const mockCategories: Category[] = [
  {
    _id: 'cat-1',
    _type: 'category',
    name: 'Running Shoes',
    slug: { current: 'running-shoes' },
    description: 'Professional running shoes for all terrains',
  },
  {
    _id: 'cat-2',
    _type: 'category',
    name: 'Casual Shoes',
    slug: { current: 'casual-shoes' },
    description: 'Comfortable everyday shoes',
  },
  {
    _id: 'cat-3',
    _type: 'category',
    name: 'Formal Shoes',
    slug: { current: 'formal-shoes' },
    description: 'Elegant shoes for formal occasions',
  },
  {
    _id: 'cat-4',
    _type: 'category',
    name: 'Sports Shoes',
    slug: { current: 'sports-shoes' },
    description: 'High-performance sports footwear',
  },
];

export const mockBrands: Brand[] = [
  {
    _id: 'brand-1',
    _type: 'brand',
    name: 'Nike',
    slug: { current: 'nike' },
  },
  {
    _id: 'brand-2',
    _type: 'brand',
    name: 'Adidas',
    slug: { current: 'adidas' },
  },
  {
    _id: 'brand-3',
    _type: 'brand',
    name: 'Puma',
    slug: { current: 'puma' },
  },
  {
    _id: 'brand-4',
    _type: 'brand',
    name: 'New Balance',
    slug: { current: 'new-balance' },
  },
];

export const mockProducts: Product[] = [
  {
    _id: 'prod-1',
    _type: 'product',
    name: 'Premium Running Shoe Pro',
    slug: { current: 'premium-running-shoe-pro' },
    description: 'Ultimate comfort and performance for serious runners. Features advanced cushioning technology.',
    brand: { _ref: 'brand-1', _type: 'reference' } as any,
    category: { _ref: 'cat-1', _type: 'reference' } as any,
    gender: 'men',
    price: 85000,
    discountPrice: 70000,
    mainImage: {
      _type: 'image',
      asset: { _ref: 'image-1', _type: 'reference' },
    },
    images: [],
    variants: [
      {
        colorName: 'Black',
        colorHex: '#000000',
        images: [],
      },
      {
        colorName: 'Blue',
        colorHex: '#0000FF',
        images: [],
      },
    ],
    sizes: [
      { sizeLabel: '38', inStock: true, stockQty: 5 },
      { sizeLabel: '39', inStock: true, stockQty: 8 },
      { sizeLabel: '40', inStock: true, stockQty: 3 },
      { sizeLabel: '41', inStock: false, stockQty: 0 },
      { sizeLabel: '42', inStock: true, stockQty: 6 },
    ],
    tags: ['new', 'sale'],
    isFeatured: true,
    isBestSeller: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-2',
    _type: 'product',
    name: 'Classic Casual Sneaker',
    slug: { current: 'classic-casual-sneaker' },
    description: 'Timeless design meets modern comfort. Perfect for everyday wear.',
    brand: { _ref: 'brand-2', _type: 'reference' } as any,
    category: { _ref: 'cat-2', _type: 'reference' } as any,
    gender: 'unisex',
    price: 65000,
    mainImage: {
      _type: 'image',
      asset: { _ref: 'image-2', _type: 'reference' },
    },
    images: [],
    variants: [
      {
        colorName: 'White',
        colorHex: '#FFFFFF',
        images: [],
      },
      {
        colorName: 'Gray',
        colorHex: '#808080',
        images: [],
      },
    ],
    sizes: [
      { sizeLabel: '36', inStock: true, stockQty: 4 },
      { sizeLabel: '37', inStock: true, stockQty: 7 },
      { sizeLabel: '38', inStock: true, stockQty: 9 },
      { sizeLabel: '39', inStock: true, stockQty: 5 },
      { sizeLabel: '40', inStock: true, stockQty: 6 },
      { sizeLabel: '41', inStock: true, stockQty: 3 },
      { sizeLabel: '42', inStock: true, stockQty: 8 },
    ],
    tags: ['popular'],
    isFeatured: true,
    isBestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-3',
    _type: 'product',
    name: 'Elite Basketball High Top',
    slug: { current: 'elite-basketball-high-top' },
    description: 'Professional basketball shoe with ankle support and responsive cushioning.',
    brand: { _ref: 'brand-1', _type: 'reference' } as any,
    category: { _ref: 'cat-4', _type: 'reference' } as any,
    gender: 'men',
    price: 120000,
    discountPrice: 95000,
    mainImage: {
      _type: 'image',
      asset: { _ref: 'image-3', _type: 'reference' },
    },
    images: [],
    variants: [
      {
        colorName: 'Red',
        colorHex: '#FF0000',
        images: [],
      },
      {
        colorName: 'Black',
        colorHex: '#000000',
        images: [],
      },
    ],
    sizes: [
      { sizeLabel: '40', inStock: true, stockQty: 2 },
      { sizeLabel: '41', inStock: true, stockQty: 4 },
      { sizeLabel: '42', inStock: true, stockQty: 5 },
      { sizeLabel: '43', inStock: false, stockQty: 0 },
      { sizeLabel: '44', inStock: true, stockQty: 3 },
      { sizeLabel: '45', inStock: true, stockQty: 2 },
    ],
    tags: ['sale'],
    isFeatured: false,
    isBestSeller: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-4',
    _type: 'product',
    name: 'Women\'s Fitness Trainer',
    slug: { current: 'womens-fitness-trainer' },
    description: 'Lightweight and flexible training shoe designed for women.',
    brand: { _ref: 'brand-3', _type: 'reference' } as any,
    category: { _ref: 'cat-4', _type: 'reference' } as any,
    gender: 'women',
    price: 55000,
    mainImage: {
      _type: 'image',
      asset: { _ref: 'image-4', _type: 'reference' },
    },
    images: [],
    variants: [
      {
        colorName: 'Pink',
        colorHex: '#FFC0CB',
        images: [],
      },
      {
        colorName: 'Purple',
        colorHex: '#800080',
        images: [],
      },
    ],
    sizes: [
      { sizeLabel: '35', inStock: true, stockQty: 6 },
      { sizeLabel: '36', inStock: true, stockQty: 7 },
      { sizeLabel: '37', inStock: true, stockQty: 5 },
      { sizeLabel: '38', inStock: true, stockQty: 4 },
      { sizeLabel: '39', inStock: true, stockQty: 3 },
    ],
    tags: ['new'],
    isFeatured: true,
    isBestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-5',
    _type: 'product',
    name: 'Kids Adventure Explorer',
    slug: { current: 'kids-adventure-explorer' },
    description: 'Durable and fun shoes for active kids. School and playground approved.',
    brand: { _ref: 'brand-4', _type: 'reference' } as any,
    category: { _ref: 'cat-2', _type: 'reference' } as any,
    gender: 'kids',
    price: 35000,
    mainImage: {
      _type: 'image',
      asset: { _ref: 'image-5', _type: 'reference' },
    },
    images: [],
    variants: [
      {
        colorName: 'Orange',
        colorHex: '#FFA500',
        images: [],
      },
      {
        colorName: 'Green',
        colorHex: '#008000',
        images: [],
      },
    ],
    sizes: [
      { sizeLabel: '25', inStock: true, stockQty: 4 },
      { sizeLabel: '26', inStock: true, stockQty: 5 },
      { sizeLabel: '27', inStock: true, stockQty: 6 },
      { sizeLabel: '28', inStock: true, stockQty: 3 },
      { sizeLabel: '29', inStock: false, stockQty: 0 },
      { sizeLabel: '30', inStock: true, stockQty: 2 },
    ],
    tags: ['new', 'popular'],
    isFeatured: false,
    isBestSeller: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-6',
    _type: 'product',
    name: 'Elegant Formal Oxford',
    slug: { current: 'elegant-formal-oxford' },
    description: 'Sophisticated leather Oxford shoe perfect for business and formal events.',
    brand: { _ref: 'brand-2', _type: 'reference' } as any,
    category: { _ref: 'cat-3', _type: 'reference' } as any,
    gender: 'men',
    price: 95000,
    mainImage: {
      _type: 'image',
      asset: { _ref: 'image-6', _type: 'reference' },
    },
    images: [],
    variants: [
      {
        colorName: 'Black',
        colorHex: '#000000',
        images: [],
      },
      {
        colorName: 'Brown',
        colorHex: '#8B4513',
        images: [],
      },
    ],
    sizes: [
      { sizeLabel: '40', inStock: true, stockQty: 3 },
      { sizeLabel: '41', inStock: true, stockQty: 4 },
      { sizeLabel: '42', inStock: true, stockQty: 5 },
      { sizeLabel: '43', inStock: true, stockQty: 2 },
      { sizeLabel: '44', inStock: true, stockQty: 3 },
      { sizeLabel: '45', inStock: false, stockQty: 0 },
    ],
    tags: [],
    isFeatured: false,
    isBestSeller: true,
    createdAt: new Date().toISOString(),
  },
];

export const mockStoreSettings: StoreSettings = {
  _id: 'settings',
  _type: 'storeSettings',
  storeName: 'My Shoes Rwanda',
  whatsappNumber: '250788000000',
  defaultCurrency: 'RWF',
  deliveryFees: {
    kigali: 2000,
    other: 5000,
  },
  paymentInstructions: 'Mobile Money (MTN, Airtel) or Bank Transfer upon order confirmation',
  returnPolicy: '30-day return policy for unworn shoes with original packaging',
  socialLinks: {
    instagram: 'https://instagram.com/myshoesrwanda',
    facebook: 'https://facebook.com/myshoesrwanda',
  },
};
